### ISSUE TITLE
`/pw setspawn` seems to round coordinates to integers

### ISSUE THREAD

**Issue by Andre601** [lokka30/PhantomWorlds#33]
When setting the spawnpoint using f.e. `/pw setspawn 0.5 100 0.5 world 0 0` and then use `/pw tp world` will PhantomWorld always teleport to the next negative whole number of the coordinates you set.
In our above example would this result in `0 100 0` which is annoying as you always end up in the corner of a block while you may want to have a precise position instead.

So it would be nice, if PhantomWorld would respect decimals in a spawn location.

**Comment by lokka30** [comment]
Thanks for opening the issue Andre. :)

At first I thought I was accidentally using doubles instead of decimals somewhere in the code, although [PW is definitely using doubles](https://github.com/lokka30/PhantomWorlds/blob/master/src/main/java/me/lokka30/phantomworlds/commands/phantomworlds/subcommands/SetSpawnSubcommand.java#L92).

This means there is an issue with Spigot/Minecraft not storing `World#getSpawnLocation` values as doubles.

However I am absolutely able to add PhantomWorlds' own spawn-location data, which can set Minecraft's spawn location but the `/pw teleport` command will use PhantomWorlds' own data to ensure the double value is teleported to.

What do you think? :)

**Comment by lokka30** [comment]
I aim to resolve this either in PW v2.1 or v2.2.

**Comment by Andre601** [comment]
> Thanks for opening the issue Andre. :)
> 
> At first I thought I was accidentally using doubles instead of decimals somewhere in the code, although [PW is definitely using doubles](https://github.com/lokka30/PhantomWorlds/blob/master/src/main/java/me/lokka30/phantomworlds/commands/phantomworlds/subcommands/SetSpawnSubcommand.java#L92).
> 
> This means there is an issue with Spigot/Minecraft not storing `World#getSpawnLocation` values as doubles.
> 
> However I am absolutely able to add PhantomWorlds' own spawn-location data, which can set Minecraft's spawn location but the `/pw teleport` command will use PhantomWorlds' own data to ensure the double value is teleported to.
> 
> What do you think? :)

Sounds like a solution, although I personally doubt that Spigot doesn't support double for worldspawn locations, unless plugins like Multiverse-Core utilize their own internal storing and usage of locations...

**Comment by lokka30** [comment]
> 
> 
> > Thanks for opening the issue Andre. :)
> > At first I thought I was accidentally using doubles instead of decimals somewhere in the code, although [PW is definitely using doubles](https://github.com/lokka30/PhantomWorlds/blob/master/src/main/java/me/lokka30/phantomworlds/commands/phantomworlds/subcommands/SetSpawnSubcommand.java#L92).
> > This means there is an issue with Spigot/Minecraft not storing `World#getSpawnLocation` values as doubles.
> > However I am absolutely able to add PhantomWorlds' own spawn-location data, which can set Minecraft's spawn location but the `/pw teleport` command will use PhantomWorlds' own data to ensure the double value is teleported to.
> > What do you think? :)
> 
> Sounds like a solution, although I personally doubt that Spigot doesn't support double for worldspawn locations, unless plugins like Multiverse-Core utilize their own internal storing and usage of locations...

I believe that is the case - since [I am using doubles (and floats for pitch/yaw) the entire way through](https://github.com/lokka30/PhantomWorlds/blob/dev/src/main/java/me/lokka30/phantomworlds/commands/phantomworlds/subcommands/SetSpawnSubcommand.java#L168). Perhaps I could do some debug console logging to ensure the values being sent in `World#setSpawnLocation` are definitely the intended numbers.

The only modification to the numbers done is that the decimals are rounded to two places, although now that I think of it, it would be better to only round it for the messages, not for the entire variable itself since that was what it was created for.

**Comment by creatorfromhell** [comment]
> > Thanks for opening the issue Andre. :)
> > At first I thought I was accidentally using doubles instead of decimals somewhere in the code, although [PW is definitely using doubles](https://github.com/lokka30/PhantomWorlds/blob/master/src/main/java/me/lokka30/phantomworlds/commands/phantomworlds/subcommands/SetSpawnSubcommand.java#L92).
> > This means there is an issue with Spigot/Minecraft not storing `World#getSpawnLocation` values as doubles.
> > However I am absolutely able to add PhantomWorlds' own spawn-location data, which can set Minecraft's spawn location but the `/pw teleport` command will use PhantomWorlds' own data to ensure the double value is teleported to.
> > What do you think? :)
> 
> Sounds like a solution, although I personally doubt that Spigot doesn't support double for worldspawn locations, unless plugins like Multiverse-Core utilize their own internal storing and usage of locations...

If you look at the Javadocs, for the setSpawn methods beyond location, spigot explicitly uses integers for the parameters, I wouldn't be surprised if there was an internal restriction from the data provided by the Location object too. Looking at MV, they use the block coords when they use the setSpawn(location object) method which may be a sign that Spigot or Minecraft does indeed, very dumbly, round these values. (has been corrected on my fork)

**Comment by lokka30** [comment]
Cheers @creatorfromhell - @Andre601, see [this](https://github.com/TheNewEconomy/PhantomWorlds/) fork :)
